server:
  port: 8085
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: dbb_admin
    password: admin
  artemis:
    user: developer
    password: developer
    brokerUrl: tcp://localhost:61616
jms:
  queue:
    destination:
      listen: check
      send: validate
